### ISSUE TITLE
Stuck at 17% for install

### ISSUE THREAD

**Issue by MetalLinx** [datdamnzotz/FoundryVTT-Game-Audio-Bundle-2#1]
Bundle 1 installed without any apparent issues. This bundle gets stuck at 17% for me when installing in Foundry VTT. Some audio files at the top of the compendium list for this bundle will function if ignored.

**Comment by datdamnzotz** [comment]
Could be the host that is running VTT is having problems downloading from github. (or github is having problems)
Check your disk space make sure your not full. 

You can always download the pack manually if VTT is timing out on the download.
Grab the zip from https://github.com/datdamnzotz/FoundryVTT-Game-Audio-Bundle-2/releases and unzip to your modules directory.

Then restart VTT.  It should show up then.

**Comment by datdamnzotz** [comment]
Resolved?

**Comment by MetalLinx** [comment]
Version 2.0 fixed the issue regardless of what the original issue was. Thanks for the work! Resolved.
